### ISSUE TITLE
Fix small grid issues

### ISSUE THREAD

**Issue by magnusrodseth** [magnusrodseth/sobekkseter#7]
**Tasks**

- [x] Make grid flow a bit prettier. I'm thinking filling up whitespace is the way to go.

<img width="1680" alt="Skjermbilde 2021-06-13 kl  12 56 43" src="https://user-images.githubusercontent.com/59113973/121804477-e5327b80-cc46-11eb-9aaa-174d692c63a1.png">

As seen in the screenshot above, whitespace should be filled using grid CSS with Tailwind.

Further, there is a small portion where the webcam image and average data is placed on top. I don’t know why, but needs to be looked into.

- [x] Fix styling error between `md` (medium) and `sm` (small). Place webcam image on top and average data at the bottom.
 
<img width="1680" alt="Skjermbilde 2021-06-13 kl  12 58 52" src="https://user-images.githubusercontent.com/59113973/121804528-1ca12800-cc47-11eb-8956-e80663f05690.png">

- [x] Vertical and horizontal responsiveness should be 100% working due to using Tailwind grid. Ensure that this still holds after fixing the styling error mentioned above.
